pool:
  sort_by:
    size: true
    publish_time: true
snippets:
  PRJ_DEFAULT:
    size:
    - [0, 100]
    publish_within: 660
    seeder: [-1, 5]
    leecher: [-1, 5000]
    snatch: [-1, 5]
    free_time_min: 21000
    hr_time_max: 432000
    hr_seed_delay: 1800
    ignore_hr_leeching: true
    load_balance_key: 'upload_speed * 8 / bandwidth'
  RM_DEFAULT:
    remove_conditions:
    - info: '种子下载速度过慢'
      exp: 'active_time >= 86400 and progress < 10'
      period: L
    - info: '活动时长超过限制'
      exp: 'active_time >= 432000'
      period: B
    - info: '做种时长达到要求'
      exp: 'seeding_time >= size / 1073741824 * 1.0 * 60'
      period: S
    tracker_message_remove: '(?i)not.*reg|not.*auth|delete|remove|dupe|trump|rev|nuke|same|diff|loc|收|除|撤|同|重'
clients:
  de1:
    type: deluge
    host: '127.0.0.1:58846'
    user: 'localclient'
    pass: 'deluge'
    bandwidth: 1000
    task_count_max: 10
    download_speed_max: 90
  qb1:
    type: qbittorrent
    host: 'http://127.0.0.1:8080'
    user: 'admin'
    pass: 'admin'
    bandwidth: 200
    task_count_max: 10
    download_speed_max: 90
volumes:
  disk1: 4396
  disk2: 2215
sites:
  CHDBits:
    rss: 'https://chdbits.co/torrentrss.php?rows=50&isize=1&linktype=dl&passkey='
    web:
    - 'https://chdbits.co/torrents.php?sort=4&type=desc'
    cookies:
      c_secure_login: '...'
      c_secure_pass: '...'
      c_secure_ssl: '...'
      c_secure_tracker_ssl: '...'
      c_secure_uid: '...'
    hr_min_progress: 50
    web_interval: 10
  HDChina:
    rss: 'https://hdchina.org/torrentrss.php?rows=50&isize=1&linktype=dl&passkey='
  HDSky:
    rss: 'https://hdsky.me/torrentrss.php?rows=50&isize=1&linktype=dl&passkey='
    web:
    - 'https://hdsky.me/torrents.php?sort=4&type=desc'
    cookies:
      c_secure_login: '...'
      c_secure_pass: '...'
      c_secure_ssl: '...'
      c_secure_tracker_ssl: '...'
      c_secure_uid: '...'
    retry_pause_count: 4
  MTeam:
    rss: 'https://kp.m-team.cc/torrentrss.php?rows=50&isize=1&https=1&linktype=dl&passkey='
    web:
    - 'https://kp.m-team.cc/torrents.php?sort=4&type=desc'
    - 'https://kp.m-team.cc/adult.php?sort=4&type=desc'
    - 'https://kp.m-team.cc/music.php?sort=4&type=desc'
    cookies:
      tp: '...'
    retry_pause_count: 4
  OpenCD:
    rss: 'https://open.cd/torrentrss.php?rows=50&isize=1&linktype=dl&passkey='
    web:
    - 'https://open.cd/torrents.php?sort=4&type=desc'
    cookies:
      c_secure_login: '...'
      c_secure_pass: '...'
      c_secure_ssl: '...'
      c_secure_tracker_ssl: '...'
      c_secure_uid: '...'
    fetch_interval: 60
    retry_interval: 10
  OurBits:
    rss: 'https://ourbits.club/torrentrss.php?rows=50&isize=1&https=1&linktype=dl&passkey='
    web:
    - 'https://ourbits.club/torrents.php?sort=4&type=desc'
    cookies:
      ourbits_jwt: '...'
    hr_seed_ratio: 1.0
    hr_min_progress: 10
  SSD:
    rss: 'https://springsunday.net/torrentrss.php?rows=50&isize=1&https=1&linktype=dl&passkey='
    web:
    - 'https://springsunday.net/torrents.php?sort=4&type=desc'
    cookies:
      SPRINGID: '...'
  TTG:
    rss: 'https://totheglory.im/putrss.php?ssl=yes&par='
    hr_seed_ratio: 1.0
    hr_min_progress: 10
  U2:
    rss: 'https://u2.dmhy.org/torrentrss.php?rows=50&isize=1&trackerssl=1&linktype=dl&passkey='
    web:
    - 'https://u2.dmhy.org/torrents.php?sort=4&type=desc'
    cookies:
      nexusphp_u2: '...'
projects:
  U2_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    clients:
      de1:
        volume: disk1
        path: '/mnt/U2'
        extra_options: {'max_upload_speed': 51200}
      qb1:
        volume: disk2
        path: 'C:\U2'
        extra_options: {'upLimit': 52428800}
    sites:
    - U2
    free_only: true
  HDC_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    clients:
      de1:
        volume: disk1
        path: '/mnt/HDC'
      qb1:
        volume: disk2
        path: 'C:\HDC'
    sites:
    - HDChina
    regexp:
    - '[-@]HDC'
  TTG_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    clients:
      de1:
        volume: disk1
        path: '/mnt/TTG'
      qb1:
        volume: disk2
        path: 'C:\TTG'
    sites:
    - TTG
    regexp:
    - '[-@](TTG|WiKi|NGB|DoA|ARiN)'
  CHD_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    clients:
      de1:
        volume: disk1
        path: '/mnt/CHD'
      qb1:
        volume: disk2
        path: 'C:\CHD'
    sites:
    - CHDBits
    regexp:
    - '-CHD(?!Bits)'
    - '@CHD'
    - '[-@]OneHD'
    free_only: true
    ignore_hr_leeching: false
  HDS_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    clients:
      de1:
        volume: disk1
        path: '/mnt/HDS'
      qb1:
        volume: disk2
        path: 'C:\HDS'
    sites:
    - HDSky
    regexp:
    - '[-@]HDS'
    - 'WOWOW|NHK|TVAsahi'
    free_only: true
  SSD_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    clients:
      de1:
        volume: disk1
        path: '/mnt/SSD'
      qb1:
        volume: disk2
        path: 'C:\SSD'
    sites:
    - SSD
    regexp:
    - '[-@]CMCT'
    free_only: true
  OB_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    clients:
      de1:
        volume: disk1
        path: '/mnt/OB'
        extra_options: {'max_upload_speed': 51200}
      qb1:
        volume: disk2
        path: 'C:\OB'
        extra_options: {'upLimit': 52428800}
    sites:
    - OurBits
    regexp:
    - '[-@](Our|iLove|PbK|FLTTH)'
    free_only: true
  OTHERS_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    clients:
      de1:
        volume: disk1
        path: '/mnt/OTHERS'
      qb1:
        volume: disk2
        path: 'C:\OTHERS'
    sites:
    - MTeam
    - OpenCD
    free_only: true
