sort_by:
  size: true
  publish_time: true
snippets:
  PRJ_DEFAULT:
    size:
    - [0, 100]
    publish_within: 660
    seeder: [0, 5]
    leecher: [0, 5000]
    snatch: [0, 5]
    free_only: true
    free_time_min: 21000
    free_end_escape: true
    hr_time_max: 432000
    hr_seed_delay: 1800
    ignore_hr_leeching: true
    task_count_max: 10
  RM_DEFAULT:
    remove_conditions:
    - info: '种子下载速度过慢'
      exp: 'active_time >= 86400 and progress < 10'
      period: L
    - info: '活动时长超过限制'
      exp: 'active_time >= 432000'
      period: B
    - info: '做种时长达到要求'
      exp: 'seeding_time >= size / 1073741824 * 1.0 * 60'
      period: S
clients:
  de1:
    type: deluge
    host: '127.0.0.1:58846'
    user: 'localclient'
    pass: 'deluge'
    task_count_max: 10
  qb1:
    type: qbittorrent
    host: 'http://127.0.0.1:8080'
    user: 'admin'
    pass: 'admin'
    task_count_max: 10
volumes:
  disk1: 4396
  disk2: 2215
sites:
  CHDBits:
    rss: 'https://chdbits.co/torrentrss.php?rows=50&isize=1&linktype=dl&passkey='
    web:
    - 'https://chdbits.co/torrents.php?sort=4&type=desc'
    cookies:
      c_secure_login: '...'
      c_secure_pass: '...'
      c_secure_ssl: '...'
      c_secure_tracker_ssl: '...'
      c_secure_uid: '...'
    priority: 4
  HDSky:
    rss: 'https://hdsky.me/torrentrss.php?rows=50&isize=1&linktype=dl&passkey='
    web:
    - 'https://hdsky.me/torrents.php?sort=4&type=desc'
    cookies:
      c_secure_login: '...'
      c_secure_pass: '...'
      c_secure_ssl: '...'
      c_secure_tracker_ssl: '...'
      c_secure_uid: '...'
    priority: 5
  MTeam:
    rss: 'https://kp.m-team.cc/torrentrss.php?rows=50&isize=1&https=1&linktype=dl&passkey='
    web:
    - 'https://kp.m-team.cc/torrents.php?sort=4&type=desc'
    - 'https://kp.m-team.cc/adult.php?sort=4&type=desc'
    - 'https://kp.m-team.cc/music.php?sort=4&type=desc'
    cookies:
      tp: '...'
    priority: 2
  OpenCD:
    rss: 'https://open.cd/torrentrss.php?rows=50&isize=1&linktype=dl&passkey='
    web:
    - 'https://open.cd/torrents.php?sort=4&type=desc'
    cookies:
      c_secure_login: '...'
      c_secure_pass: '...'
      c_secure_ssl: '...'
      c_secure_tracker_ssl: '...'
      c_secure_uid: '...'
    fetch_interval: 60
    retry_interval: 10
    priority: 8
  OurBits:
    rss: 'https://ourbits.club/torrentrss.php?rows=50&isize=1&https=1&linktype=dl&passkey='
    web:
    - 'https://ourbits.club/torrents.php?sort=4&type=desc'
    cookies:
      ourbits_jwt: '...'
    priority: 7
  SSD:
    rss: 'https://springsunday.net/torrentrss.php?rows=50&isize=1&https=1&linktype=dl&passkey='
    web:
    - 'https://springsunday.net/torrents.php?sort=4&type=desc'
    cookies:
      SPRINGID: '...'
    priority: 6
  TTG:
    rss: 'https://totheglory.im/putrss.php?ssl=yes&par='
    web:
    - 'https://totheglory.im/browse.php?c=M&sort=4&type=desc'
    - 'https://totheglory.im/browse.php?c=G&sort=4&type=desc'
    cookies:
      laccess: '...'
      pass: '...'
      uid: '...'
    priority: 3
  U2:
    rss: 'https://u2.dmhy.org/torrentrss.php?rows=50&isize=1&trackerssl=1&linktype=dl&passkey='
    web:
    - 'https://u2.dmhy.org/torrents.php?sort=4&type=desc'
    cookies:
      nexusphp_u2: '...'
    priority: 1
projects:
  U2_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    client: de1
    path: '/mnt/U2'
    volume: disk1
    sites:
    - U2
    extra_options: {'max_upload_speed': 52428800}
  MT_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    client: de1
    path: '/mnt/MT'
    volume: disk1
    sites:
    - MTeam
  TTG_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    client: qb1
    path: 'C:\TTG'
    volume: disk2
    sites:
    - TTG
    regexp:
    - '(-|@)(TTG|WiKi|NGB|DoA|ARiN)'
    hr_seed_ratio: 1.0
  CHD_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    client: de1
    path: '/mnt/CHD'
    volume: disk1
    sites:
    - CHDBits
    regexp:
    - '-CHD(?!Bits)'
    - '@CHD'
    - '(-|@)OneHD'
    ignore_hr_leeching: false
  HDS_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    client: de1
    path: '/mnt/HDS'
    volume: disk1
    sites:
    - HDSky
    regexp:
    - '(-|@)HDS'
    - 'WOWOW|NHK|TVAsahi'
  SSD_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    client: de1
    path: '/mnt/SSD'
    volume: disk1
    sites:
    - SSD
    regexp:
    - '(-|@)CMCT'
  OB_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    client: de1
    path: '/mnt/OB'
    volume: disk1
    sites:
    - OurBits
    regexp:
    - '(-|@)(Our|iLove|PbK|FLTTH)'
    hr_seed_ratio: 1.0
    extra_options: {'max_upload_speed': 52428800}
  OCD_new:
    snippets:
    - PRJ_DEFAULT
    - RM_DEFAULT
    client: de1
    path: '/mnt/OCD'
    volume: disk1
    sites:
    - OpenCD
